spring.datasource.url=jdbc:postgresql://localhost:5432/message_db
spring.datasource.username=message
spring.datasource.password=message

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

server.port=8080

spring.output.ansi.enabled=ALWAYS
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss

logging.level.com.gshelgaas.messageserver=DEBUG
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO